spring:
  application:
    name: "configserver"
  profiles:
#    local config
#    active: native
      active: git
  cloud:
    config:
      server:
#        native:
#          classpath
#          search-locations: "classpath:/config"
#          file
#          search-locations: "file:///D:/microservcie-project/v2 - spring cloud config/banking-microservices/configserver/src/main/resources/config"
        git:
          uri: "https://github.com/BhaskarChauhan/ams-config.git"
          username: BhaskarChauhan
          password: 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
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    post: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
encrypt:
  key: "0423RUGWFF04BT54GE90843278YRUR"

server:
  port: 8071

