services:
  accounts:
    image: bhaskarchauhan/accounts:0.0.1-SNAPSHOT
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 200m
    networks:
      - ASPL
  loans:
    image: bhaskarchauhan/loans:0.0.1-SNAPSHOT
    container_name: loans-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 650m
    networks:
      - ASPL
  cards:
    image: bhaskarchauhan/cards:0.0.1-SNAPSHOT
    container_name: cards-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 200m
    networks:
      - ASPL
networks:
  ASPL:
    driver: "bridge"