build:
  version: "1.0"
accounts:
  message: "Welcome to ASPL banks accounts Production APIs"
  contactDetails:
    name: "Bhaskar Chauhan - Product Owner"
    email: "chauhanbhaskar51@gmail.com"
  onCallSupport:
    - +91 7620264927
    - +91 8605037960