build:
  version: "2.0"
cards:
  message: "Welcome to ASPL banks cards QA APIs"
  contactDetails:
    name: "Bhaskar Chauhan - QA"
    email: "chauhanbhaskar51@gmail.com"
  onCallSupport:
    - +91 7620264927
    - +91 8605037960