server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"

build:
  version: "1.0"

cards:
  message: "Welcome to ASPL banks cards local APIs"
  contactDetails:
    name: "Bhaskar Chauhan - Developer"
    email: "chauhanbhaskar51@gmail.com"
  onCallSupport:
    - +91 7620264927
    - +91 8605037960